import { ContentLayout } from "@/components/ContentLayout";

export default function AboutPage() {
  return (
    <ContentLayout
      title="About"
      breadcrumbs={[{ label: "Home", href: "/" }, { label: "About" }]}
    >
      <h2 className="text-lg font-semibold mt-4">Our Mission</h2>
      <p>
        We aim to collaborate with underprivileged communities to create comprehensive, interactive, image-driven information pages that help students see the big picture when studying anatomy. We will then use the revenue generated by the site to directly support those communities.
      </p>

      <h2 className="text-lg font-semibold mt-6">Educational Approach</h2>
      <p>
        The goal is to focus on the <em>why</em> behind anatomical structures, not just the <em>what</em>, to make knowledge more meaningful and easier to retain. For example, instead of simply asking <em>&quot;What is the greater tubercle of the humerus?&quot;</em>, these information pages encourage students to ask <em>&quot;Why is the greater tubercle a named structure, and what role does it play?&quot;</em>
      </p>

      <h2 className="text-lg font-semibold mt-6">Feedback</h2>
      <p>
        If you have suggestions for improving this website or its study sheets, please share them at{" "}
        <a href="mailto:emiliasavich@gmail.com">emiliasavich@gmail.com</a> (our official email is coming soon).
      </p>
    </ContentLayout>
  );
}
